### ISSUE TITLE
Build a timer feature

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-data-input-client#94] opened 2020-11-17 18:27 UTC
As a user, I want to be able to keep track of when tests are ready to be read with a timer in the app

Each card in the test queue should have a timer that can run for 15 minutes

**Comment by timothybest-usds** [comment] 2020-12-01 14:23
Needs Mockup

**Comment by aliciabeckett-gov** [comment] 2020-12-08 16:06
Dupe of prime-central #121

**Closed** 2020-12-08 16:06 UTC
Labels: Design, Enhancement, Incomplete
